[time]
disabled = false
format = '[\[ $time \]]($style) '
time_format = "%T"

[nodejs]
disabled = true

[git_status]
disabled = true

[cmd_duration]
min_time = 500
format = "took [$duration](bold yellow)"

[battery]
disabled = true

[git_metrics]
disabled = false

[lua]
disabled = true

[container]
disabled = true

[jobs]
disabled = true
